### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MartinWa**
Added section on how to configure displayport_msp_serial for softserial and also how to verify that displayport_msp_serial is correct.

### CODE REVIEW

**Review by mavenius — APPROVED** [review]

**Comment by MartinWa** [comment]
I can add that I have tested msp-osd over soft serial today on a F411 FC (GEP-F411-35A AIO) and it does work. The OSD text elements are flickering, probably due to the fact that the CPU does not have time to update at the speed needed. Perhaps this can be solved by reducing CPU load or lowering the softserial baud rate. Nevertheless, it works well enough to fly and is a huge improvement over DJI OSD. (Betaflight menus are however tricky to use as all text is not drawn and updated).

**Comment by LouDnl** [comment]
Have you tried ```set displayport_msp_use_device_blink = ON```?
On HDZero this helped with blinking OSD items.

**Comment by MartinWa** [comment]
`set displayport_msp_use_device_blink = ON` did not help unfortunately

**Comment by LouDnl** [comment]
Thanks for testing though.

**Comment by benlumley** [comment]
Thanks!

**Pull request merged**
