### PR TITLE
DJI Overlay Support

### PR DESCRIPTION
**Pull request by bri3d**
In this PR we:
* Refactor to use the NDK build system.
* Build a shared object using the fpv-wtf modloader system, which allows us to inject our code into a running dji_glasses process.
* Refactor to extract the pointer to the DJI display device and ION shared memory from the dji_glasses process so we can share them with dji_glasses.
* Tweak the overlay OSD to co-exist with the DJI one.

The net effect of installing this IPK is that you will get MSP OSD on top of the DJI one.

There are known issues:
* If you have a font on the SD card, removing the SD card or plugging in USB will crash dji_glasses and cause it to restart.
* There is no good way to hide the OSD, so it will sit on top of your menus and annoy you.
* The OSD does not disappear when link is lost. This is both a feature and a bug, but combined with the prior, it's kind of annoying.

Otherwise, everything should work - channel changing, recording, settings, we're back in action!!!

### CODE REVIEW

**Comment by DimitarKrastev** [comment]
If the two OSDs coexist does that mean we will see two OSDs on top of each other? Is there a way disable the DJI OSD otherwise two pairs of OSD will be cluttered and unreadable. Maybe setting custom OSD to off in DJI settings menu?

**Comment by bri3d** [comment]
Yes, exactly that.

**Comment by bike797** [comment]
If I apply this pr, can I use the recording function of the goggles and the msp osd at the same time?

**Comment by j005u** [comment]
Yes, but you don't need to apply the PR, you can just update to the latest version through the configurator.

**Comment by bike797** [comment]
just before this pr, i have on/off soulution about MSP OSD mode 
 - ""Press back button for five seconds to enter/exit MSP OSD mode.""

after this pr, we don't have any on/off switch(enter/exit MSP OSD mode)?

**Pull request merged**
