### PR TITLE
ipk package creation

### PR DESCRIPTION
**Pull request by stylesuxx**
Added functionality to build an **ipk package** which can then be installed via `opkg`.

The plan is to now do the same thing for the airunit part - I think it makes sense to separate the packages by goggle and airunit. I submitted this as a draft for now, just so we can have a place to talk about.

@bri3d I added another check for the font to live in the entware env, my editor removed some white spacing, that's why it looks as if I touch so much...

Summoning @j005u - let me know what you think regarding packaging if this makes sense to you or if you have any feedback.

### CODE REVIEW

**Comment by bri3d** [comment]
This looks pretty nice to me.

We might want to package the fonts in a different ipkg if we're going to put it in a package-maintained directory, so people can install their own separate font packages? Or maybe we should just let them put it on the SDcard (I need to make this more reliable regardless). I'm not sure. I might also need/want to implement a font switcher to go from Ardu to iNav to Betaflight in a single flying session for example, which I do from time to time.

Not a blocker by any means but food for thought.

**Comment by stylesuxx** [comment]
Custom font package makes sense - you are right. We could then add the "default font" as a dependency to this package.
But then I am not sure if it makes sense to allow the user to drop custom fonts to the SD? 

I have no idea how many fonts there are and if people are creating custom fonts? Maybe it would make sense to batch convert all of the available ones and package them up in one package - or one package per flight-controller firmware?

I think it would make sense to start talking about a custom package repository...

**Comment by j005u** [comment]
@stylesuxx Package definition looks good to me. I like that you gave it a direct dependency to dinit, I had intended for that to be the pattern to follow so things could work smoothly should we ever have reason to migrate to something else.

I would propose that we don't have different packages override the same fixed path. Rather a) have a osdfonts.d and symlink the active font into place or b) if bri3d is going to do some kind of configuration capability anyway, then just let them specify the file to be used with a relative path in this osdfonts.d or an absolute one anywhere (that way the sd card is also covered).

You already have getprop integrated, maybe a simple msp_osd.font prop or something along those lines is all we need? That way a font package could trivially set itself as the active one in their post install script.

While we're on the fonts subject, might I suggest a to-do of being able to switch the font color at load time via config so we don't end up with a bunch of font-color packages?

Let's continue the repo discussion on Discord, I have a bunch of thoughts. Could use your opinions on the matter.

**Comment by stylesuxx** [comment]
#11 supersedes this PR - closing.

**Pull request closed without merging**
